### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by Gufran** [davidtsadler/ebay-api-sdk-php#1]
Is there any docs or method reference ? at least a little hint would be helpful.

**Comment by michabbb** [comment]
@davidtsadler can you please at least add a few lines, howto generate the service classes, a two-liner would be enough for the start, because right now, i would like to use your sdk for the feed api, but it's not up2date, so i have to generate the classes for myself. it would be nice to know howto get all the files we see at https://github.com/davidtsadler/ebay-sdk-php - and instead of having nothing, a few lines would be enough for the start 🙏 *thanks*

ps... don´t know if u are familar with docker: maybe we can build a docker container for this, so that everybody is able to build all that stuff with only one single command 😏

**Comment by davidtsadler** [comment]
I'm current in the process of re-writing how the sdk is generated. I'm getting rid of the XML/XSLT and replacing it with a pure PHP solution. 

I will try and get some documentation together for the existing solution but be aware the the current process is not simple. It involves going through the eBay documentation and manually creating a bunch of XML files based upon it. 

The new method will try and use the OpenAPI files provided by eBay to generate the SDK.

**Comment by michabbb** [comment]
@davidtsadler when do you think you will have the first version of your new openapi-class-generator?

**Comment by michabbb** [comment]
@davidtsadler the openapi stuff will only work for the rest apis, but the trading api is still one of the most used ebay-apis, so a long-term support and generation should still be considered from your side, please don´t forget this. ebay has no plans to shutdown the trading api in the near future ‼️

**Comment by davidtsadler** [comment]
The new version is a least a month away. I will still be supporting the old trading apis.
